renamers = ["classified", "constant"]

[names]
constant = "○ "

[[names.classified]]
"歷 " = ["GNS3"]

[[names.classified]]
" " = ["Qemu-system-x86_64", "realvnc-vncviewer"]

[[names.classified]]
" " = ["Brave-browser"]

[[names.classified]]
" " = ["qBittorrent"]

[[names.classified]]
" " = ["code-oss"]

[[names.classified]]
" " = ["figma-linux"]

[[names.classified]]
" " = ["Wireshark"]

[[names.classified]]
" " = ["mpv"]

[[names.classified]]
" " = ["Steam"]

[[names.classified]]
"ﭮ " = ["discord"]

[[names.classified]]
"切 " = ["TelegramDesktop"]

[[names.classified]]
" " = ["gdlauncher", "Minecraft* 1.16.5"]

[[names.classified]]
" " = ["DesktopEditors"]

[[names.classified]]
" " = ["obs"]

[[names.classified]]
" " = ["Org.gnome.Nautilus"]

[[names.classified]]
" " = ["st-256color"]

[[names.classified]]
"漣 " = ["tools"]
