#!/bin/sh

# Trigger autorun
$HOME/.config/autorun/run

# Bspwm configs
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a tools state=floating
